"""empty message

Revision ID: 4ce1a812c0db
Revises: d3811911ff3d
Create Date: 2020-11-24 23:52:08.168431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce1a812c0db'
down_revision = 'd3811911ff3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('enrollment_number', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'enrollment_number')
    # ### end Alembic commands ###
