"""empty message

Revision ID: 73e5edf64225
Revises: cd78f40311db
Create Date: 2020-11-17 23:45:44.801844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e5edf64225'
down_revision = 'cd78f40311db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests', sa.Column('no_questions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'no_questions')
    # ### end Alembic commands ###
