"""empty message

Revision ID: 9bb62a5cdec7
Revises: 4ce1a812c0db
Create Date: 2020-11-28 19:47:02.154113

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bb62a5cdec7'
down_revision = '4ce1a812c0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE results ALTER COLUMN responses TYPE bytea USING responses::TEXT::BYTEA")
    # op.alter_column('results', 'responses',
    #            existing_type=postgresql.JSON(astext_type=sa.Text()),
    #            type_=sa.PickleType(),
    #            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('results', 'responses',
               existing_type=sa.PickleType(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
