"""empty message

Revision ID: dd08cbcf68bd
Revises: 73e5edf64225
Create Date: 2020-11-22 15:33:47.475475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd08cbcf68bd'
down_revision = '73e5edf64225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('marks', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests', 'status')
    op.drop_column('results', 'marks')
    # ### end Alembic commands ###
